services:
  - type: web
    name: youtube-downloader-api
    env: node
    region: oregon
    buildCommand: curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp && chmod +x yt-dlp && apt-get update && apt-get install -y ffmpeg && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: "3000"
